version: "3.9"

services:
  backend-api:
    ports:
      - "8000:8000"
    build:
        context: ./backend
        dockerfile: Dockerfile
    volumes:
      - ./backend/:/code
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --proxy-headers