"""Tablse for cards

Revision ID: 1b553578961d
Revises: 5e387f75b6d6
Create Date: 2025-01-31 21:12:59.972245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b553578961d'
down_revision: Union[str, None] = '5e387f75b6d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardtypes',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('specialcards',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('code_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['cardtypes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialcards')
    op.drop_table('cardtypes')
    # ### end Alembic commands ###
